name: RLKAN_SR_flir_x4_r
model_type: SRModel
scale: 4 # 2/3/4/8
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: OSU
    type: PairedImageDataset
    dataroot_gt: datasets/RLKA-NET/data/OSU/train_gt
    dataroot_lq: datasets/RLKA-NET/data/OSU/train_lrx4
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 32
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: OSU
    type: PairedImageDataset
    dataroot_gt: datasets/RLKA-NET/data/OSU/val_gt
    dataroot_lq: datasets/RLKA-NET/data/OSU/val_lrx4
    io_backend:
      type: disk

# network structures
network_g:
  type: RLKAN
  scale: 4 #or 3/4
  n_resblocks: 5 # 5 for MAN-tiny; 24 for MAN-light; 36 for MAN
  n_resgroups: 1
  n_feats: 180 # 48 for MAN-tiny; 60 for MAN-light; 180 for MAN

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [800000, 1200000, 140000, 1500000]
    gamma: 0.5

    #type: CosineAnnealingRestartLR
    #periods: [1600000]
    #restart_weights: [1]
    #eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e2
  save_img: true
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500